# Test 2025-05-24 at 02:17:11

name: Test
run-name: pythonDumpLocalVariables

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Dump local variables
      run: |
        python3 pythonDumpLocalVariables.py
